###Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. 

Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [12]:
import pandas as pd

In [13]:
authors = pd.DataFrame(
    {
    "author_id": [1, 2, 3],
    "author_name": ['Тургенев', 'Чехов', 'Островский']
}
)
print(authors)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [16]:
books = pd.DataFrame(
    {
        "author_id" : [1, 1, 1, 2, 2, 3, 3],
        "book_title" : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
        "price" : [450, 300, 350, 500, 450, 370, 290]
    }
)
book

   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

###Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [22]:
authors_price = pd.merge(authors, books, on="author_id", how='left')
authors_price

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [38]:
top5 = authors_price.sort_values(by="price", ascending=False).head(5)
top5

   author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [81]:
authors_stat = authors_price.groupby("author_name")["price"].agg(["min", "max", "mean"])
authors_stat.columns=["min_price", "max_price", "mean_price"]
authors_stat["mean_price"] = authors_stat["mean_price"].astype(int)
authors_stat

             min_price  max_price  mean_price
author_name
Островский         290        370         330
Тургенев           300        450         366
Чехов              450        500         475